query FILM_DETAIL($id: ID) {
  Film(id: $id) {
    id
    title
    releaseDate
    characters {
      _filmsMeta {
        count
      }
      name
      species {
        name
      }
      homeworld {
        name
      }
    }
  }
}
